<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Coffeemosele\\Wirebuilder\\' => array($baseDir . '/packages/coffeemosele/wirebuilder/src'),
    'App\\' => array($baseDir . '/app'),
);
