<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitab774321e0cfff2d60284f54733fce7f
{
    public static $prefixLengthsPsr4 = array (
        'C' => 
        array (
            'Coffeemosele\\Wirebuilder\\' => 25,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Coffeemosele\\Wirebuilder\\' => 
        array (
            0 => __DIR__ . '/../..' . '/packages/coffeemosele/wirebuilder/src',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitab774321e0cfff2d60284f54733fce7f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitab774321e0cfff2d60284f54733fce7f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitab774321e0cfff2d60284f54733fce7f::$classMap;

        }, null, ClassLoader::class);
    }
}
